# Generated by Django 6.0 on 2025-12-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_sosalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
