# Generated by Django 6.0 on 2025-12-24 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_patient_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosalert',
            name='user',
        ),
        migrations.AddField(
            model_name='sosalert',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_alerts', to='base.patient'),
        ),
    ]
