# Generated by Django 6.0 on 2026-01-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_volunteer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosalert',
            options={'ordering': ['-createdAt']},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='blood_type',
            new_name='bloodType',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='emergency_contact_name',
            new_name='emergencyContactName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='emergency_contact_phone',
            new_name='emergencyContactPhone',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='emergency_contact_relationship',
            new_name='emergencyContactRelationship',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='medical_conditions',
            new_name='medicalConditions',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='medical_record_number',
            new_name='medicalRecordNumber',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='sosalert',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='medical_training',
            new_name='medicalTraining',
        ),
        migrations.AddField(
            model_name='sosalert',
            name='location_text',
            field=models.TextField(blank=True, help_text='Manual location description when geolocation is unavailable', null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='isAvailable',
            field=models.CharField(choices=[('Immediate (within 30 mins)', 'Immediate (within 30 mins)'), ('Within 1 hour', 'Within 1 hour'), ('Scheduled / On-call', 'Scheduled / On-call'), ('Weekends', 'Weekends')], default='Immediate (within 30 mins)', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='vehicleDetails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
